"""table lots add cover col

Revision ID: 115558965d92
Revises: 3afd69d5f199
Create Date: 2021-02-16 14:18:11.615849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115558965d92'
down_revision = '3afd69d5f199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots_type', sa.Column('cover', sa.String(length=255), nullable=True, comment='封面'))
    op.add_column('lots_type', sa.Column('introduction', sa.Text(), nullable=True, comment='简介'))
    op.create_unique_constraint(None, 'user', ['account'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('lots_type', 'introduction')
    op.drop_column('lots_type', 'cover')
    # ### end Alembic commands ###
