"""add star_poetry col

Revision ID: 202b5a0c611f
Revises: 3127c1cfe544
Create Date: 2021-05-30 22:36:06.631521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202b5a0c611f'
down_revision = '3127c1cfe544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_destination', sa.Column('star_poetry', sa.String(length=255), nullable=False, comment='解释'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_destination', 'star_poetry')
    # ### end Alembic commands ###
