"""add views

Revision ID: 3127c1cfe544
Revises: fd4997368fec
Create Date: 2021-05-18 23:13:34.929934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3127c1cfe544'
down_revision = 'fd4997368fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('views', sa.Integer(), nullable=False, comment='浏览量'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'views')
    # ### end Alembic commands ###
