"""table aticle add likes col

Revision ID: 3afd69d5f199
Revises: d3727cc98f61
Create Date: 2021-02-15 20:25:00.118521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3afd69d5f199'
down_revision = 'd3727cc98f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('likes', sa.Integer(), nullable=True, comment='点赞数'))
    op.alter_column('article', 'content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='正文',
               existing_nullable=False)
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='文章标题',
               existing_nullable=False)
    op.alter_column('article', 'type',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='1原创，2转载，3书籍',
               existing_comment='文章类型',
               existing_server_default=sa.text("'1'"))
    op.alter_column('lots', 'content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               nullable=True,
               comment='签文内容',
               existing_comment='签文')
    op.alter_column('lots', 'lots_type',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='类型')
    op.alter_column('lots', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               nullable=True,
               comment='签名',
               existing_comment='名称')
    op.alter_column('lots', 'num',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='签号')
    op.alter_column('lots', 'solution',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='解签内容',
               existing_comment='签解',
               existing_nullable=True)
    op.create_unique_constraint('type_num', 'lots', ['lots_type', 'num'])
    op.alter_column('lots_type', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment=None,
               existing_comment='灵签名称',
               existing_nullable=False)
    op.alter_column('numerology', 'fate_desc',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='解释',
               existing_comment='释义',
               existing_nullable=False)
    op.alter_column('numerology', 'star_desc',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='星宿解释',
               existing_comment='星宿释义',
               existing_nullable=False)
    op.drop_index('account', table_name='user')
    op.create_index('account', 'user', ['account'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('account', table_name='user')
    op.create_index('account', 'user', ['account'], unique=True)
    op.alter_column('numerology', 'star_desc',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='星宿释义',
               existing_comment='星宿解释',
               existing_nullable=False)
    op.alter_column('numerology', 'fate_desc',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='释义',
               existing_comment='解释',
               existing_nullable=False)
    op.alter_column('lots_type', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               comment='灵签名称',
               existing_nullable=False)
    op.drop_constraint('type_num', 'lots', type_='unique')
    op.alter_column('lots', 'solution',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='签解',
               existing_comment='解签内容',
               existing_nullable=True)
    op.alter_column('lots', 'num',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='签号')
    op.alter_column('lots', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               nullable=False,
               comment='名称',
               existing_comment='签名')
    op.alter_column('lots', 'lots_type',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='类型')
    op.alter_column('lots', 'content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               nullable=False,
               comment='签文',
               existing_comment='签文内容')
    op.alter_column('article', 'type',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='文章类型',
               existing_comment='1原创，2转载，3书籍',
               existing_server_default=sa.text("'1'"))
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='文章标题',
               existing_nullable=False)
    op.alter_column('article', 'content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_general_ci'),
               comment='正文',
               existing_nullable=False)
    op.drop_column('article', 'likes')
    # ### end Alembic commands ###
