"""add course table

Revision ID: b8db1f82cd62
Revises: 115558965d92
Create Date: 2021-04-29 22:33:43.180503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8db1f82cd62'
down_revision = '115558965d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='章节名称'),
    sa.Column('course_id', sa.String(length=32), nullable=False, comment='课程ID'),
    sa.Column('video_url', sa.String(length=255), nullable=True, comment='视频地址'),
    sa.Column('pid', sa.String(length=32), nullable=False, comment='上一章节ID'),
    sa.Column('nid', sa.String(length=32), nullable=False, comment='下一章节ID'),
    sa.Column('parent', sa.String(length=32), nullable=False, comment='父章节ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False, comment='管理员ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='课程标题'),
    sa.Column('introduction', sa.Text(), nullable=False, comment='简介'),
    sa.Column('cover', sa.String(length=255), nullable=False, comment='封面'),
    sa.Column('author', sa.String(length=64), nullable=False, comment='作者'),
    sa.Column('type', sa.Integer(), nullable=False, comment='类型,1原创,2转载'),
    sa.Column('likes', sa.Integer(), nullable=False, comment='点赞数'),
    sa.Column('is_publication', sa.Boolean(), nullable=False, comment='是否发布'),
    sa.Column('is_free', sa.Boolean(), nullable=False, comment='是否免费'),
    sa.Column('marked_price', sa.DECIMAL(precision=6, scale=2), nullable=False, comment='标价'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_title', 'course', ['title'], unique=False)
    op.create_table('user_browse_log',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False, comment='记录类型'),
    sa.Column('user_id', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('model_id', sa.String(length=32), nullable=False, comment='类型ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('model', 'user_browse_log', ['model'], unique=False)
    op.create_index('user_id', 'user_browse_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='user_browse_log')
    op.drop_index('model', table_name='user_browse_log')
    op.drop_table('user_browse_log')
    op.drop_index('idx_title', table_name='course')
    op.drop_table('course')
    op.drop_table('chapter')
    # ### end Alembic commands ###
