"""init

Revision ID: d3727cc98f61
Revises:
Create Date: 2021-01-16 19:22:23.655019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'd3727cc98f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_destination',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour_gz', sa.String(32), nullable=False, comment='时干支'),
    sa.Column('numerology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False, comment='星名'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('numerology',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_gan', sa.String(32), nullable=False, comment='天干'),
    sa.Column('hour_gan', sa.String(32), nullable=False, comment='时干'),
    sa.Column('hexagram_name', sa.String(32), nullable=False, comment='卦名'),
    sa.Column('fate_name', sa.String(64), nullable=False, comment='格名'),
    sa.Column('fate_desc', sa.TEXT(), nullable=False, comment='释义'),
    sa.Column('fate_poetry', sa.TEXT(), nullable=False, comment='格诗'),
    sa.Column('detail', sa.TEXT(), nullable=False, comment='详情'),
    sa.Column('star_desc', sa.TEXT(), nullable=False, comment='星宿释义'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_gan', "hour_gan", name="day_hour_gan")
    )
    op.create_table('lots',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False, comment='签号'),
    sa.Column('lots_type', sa.Integer(), nullable=False, comment='类型'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='签文'),
    sa.Column('name', sa.String(64), nullable=False, comment='名称'),
    sa.Column('solution', sa.TEXT(), nullable=True, comment='签解'),
    sa.Column('poetry', sa.TEXT(), nullable=True, comment='诗文'),
    sa.Column('p_solution', sa.TEXT(), nullable=True, comment='诗解'),
    sa.Column('meaning', sa.TEXT(), nullable=True, comment='签意'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots_type',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='灵签名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False, comment='管理员ID'),
    sa.Column('title', sa.String(255), nullable=False, comment='文章标题'),
    sa.Column('introduction', sa.TEXT(), nullable=False, comment='简介'),
    sa.Column('content', mysql.LONGTEXT(), nullable=False, comment='正文'),
    sa.Column('cover', sa.String(255), nullable=True, comment='封面'),
    sa.Column('author', sa.String(32), nullable=True, comment='作者'),
    sa.Column('type', sa.Integer(), nullable=False, server_default='1', comment='文章类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_user',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True, comment='账号'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='真实姓名'),
    sa.Column('avatar', sa.String(length=128), nullable=True, comment='头像'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号码'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('ip', sa.String(length=32), nullable=True, comment='ip'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否为超管'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('admin_user_permission',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.String(length=32), nullable=False, comment='管理员ID'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='权限组ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='菜单名称'),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='父级菜单ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_group',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='权限名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='权限组描述'),
    sa.Column('permissions', sa.JSON(), nullable=False, comment='权限ID集合'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True, comment='账号'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('avatar', sa.String(length=128), nullable=True, comment='头像'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('sex', sa.Integer(), nullable=True, comment='1男，2女'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号码'),
    sa.Column('integral', sa.Integer(), nullable=True, comment='积分'),
    sa.Column('ip', sa.String(length=32), nullable=True, comment='登录IP地址'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('permission_group')
    op.drop_table('permission')
    op.drop_table('admin_user_permission')
    op.drop_table('admin_user')
    op.drop_table('article')
    op.drop_table('lots_type')
    op.drop_table('lots')
    op.drop_table('numerology')
    op.drop_table('pre_destination')
    # ### end Alembic commands ###
