"""empty message

Revision ID: fd4997368fec
Revises: b8db1f82cd62
Create Date: 2021-05-12 22:27:38.088569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4997368fec'
down_revision = 'b8db1f82cd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True, comment='服务中文名称'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('service_log',
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.String(length=64), nullable=False, comment='服务ID'),
    sa.Column('user_id', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('content', sa.JSON(), nullable=False, comment='内容'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_log')
    op.drop_table('service')
    # ### end Alembic commands ###
